.docker-login:
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

docker-build-master:
  image: docker:stable
  stage: build
  services:
    - docker:stable-dind
  extends: .docker-login
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

docker-build:
  image: docker:stable
  stage: build
  services:
    - docker:stable-dind
  extends: .docker-login
  script:
    - docker build --pull --build-arg PAPERMC_VERSION=${CI_COMMIT_REF_NAME} --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  except:
    - master
